import {
    House, LayoutDashboard, LayoutGrid, Menu, Grid3x3, Columns3,
    ChevronLeft, ChevronRight, ChevronDown, ChevronUp, ArrowLeft, ArrowRight,
    Plus, Minus, Check, PencilLine, SquarePen, Trash, Trash2, Copy, Save,
    Download, Upload, Share, Share2, ExternalLink, Link, Paperclip, Printer,
    RefreshCw, RotateCw, Undo, Redo,
    Search, Funnel, SlidersHorizontal, Eye, EyeOff, Maximize, Minimize,
    ZoomIn, ZoomOut,
    Bell, BellRing, CircleAlert, TriangleAlert, Info, CircleCheck, CircleX,
    CircleQuestionMark, Star, Heart, Bookmark, Flag, ThumbsUp, ThumbsDown,
    ChartBar, ChartBarStacked, ChartLine, ChartPie, TrendingUp, TrendingDown,
    Activity, Gauge, Database,
    ShoppingCart, ShoppingBag, CreditCard, DollarSign, Tag, Gift, Wallet,
    Receipt, Package, Truck,
    Mail, MessageSquare, MessageCircle, Send, Phone, PhoneCall, Video, Mic, MicOff,
    User, Users, UserPlus, UserMinus, UserCheck, UserX, Shield, ShieldCheck,
    File, FileText, FilePlus, Folder, FolderOpen, FolderPlus, Image,
    Calendar, CalendarDays, Clock, Timer, AlarmClock, Hourglass,
    Settings, Settings2, Cog, Key, Lock, LockOpen, LogIn, LogOut, Power,
    Cpu, Server, HardDrive, Wifi,
    Layers, Palette, Brush, Ruler, Type, Bold, Italic, Underline,
    Sun, Moon, Cloud, CloudRain, Zap, Flame, Droplet, Wind,
    MapPin, Map, Compass, Globe, Navigation,
    Play, Pause, SkipBack, SkipForward, Volume, Volume1, Volume2, VolumeX,
    Sparkles, Rocket, Trophy, Target, Lightbulb, Flower, Leaf,
    Code, Terminal, Bug, GitBranch, GitCommitHorizontal, GitPullRequest,
    MousePointer, MousePointerClick, Pointer,
    Ellipsis, EllipsisVertical, Dot,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface IconEntry {
    name: string;
    component: LucideIcon;
    tags: string[];
}

/**
 * Curated set — kept manageable for bundle size while covering the most
 * common UI needs. Search works on name + tags.
 */
export const ICON_CATALOG: IconEntry[] = [
    { name: "house", component: House, tags: ["home", "start"] },
    { name: "layout-dashboard", component: LayoutDashboard, tags: ["overview", "panels"] },
    { name: "layout-grid", component: LayoutGrid, tags: ["grid", "apps"] },
    { name: "menu", component: Menu, tags: ["hamburger", "nav"] },
    { name: "grid-3x3", component: Grid3x3, tags: ["grid"] },
    { name: "columns-3", component: Columns3, tags: ["columns", "layout"] },
    { name: "chevron-left", component: ChevronLeft, tags: ["arrow", "back"] },
    { name: "chevron-right", component: ChevronRight, tags: ["arrow", "next"] },
    { name: "chevron-down", component: ChevronDown, tags: ["arrow", "expand"] },
    { name: "chevron-up", component: ChevronUp, tags: ["arrow", "collapse"] },
    { name: "arrow-left", component: ArrowLeft, tags: ["back"] },
    { name: "arrow-right", component: ArrowRight, tags: ["next", "forward"] },

    { name: "plus", component: Plus, tags: ["add", "new"] },
    { name: "minus", component: Minus, tags: ["remove"] },
    { name: "check", component: Check, tags: ["ok", "done"] },
    { name: "pencil-line", component: PencilLine, tags: ["edit"] },
    { name: "square-pen", component: SquarePen, tags: ["edit"] },
    { name: "trash", component: Trash, tags: ["delete", "bin"] },
    { name: "trash-2", component: Trash2, tags: ["delete", "bin"] },
    { name: "copy", component: Copy, tags: ["duplicate"] },
    { name: "save", component: Save, tags: ["disk"] },
    { name: "download", component: Download, tags: ["save"] },
    { name: "upload", component: Upload, tags: [] },
    { name: "share", component: Share, tags: [] },
    { name: "share-2", component: Share2, tags: [] },
    { name: "external-link", component: ExternalLink, tags: ["open", "new tab"] },
    { name: "link", component: Link, tags: ["chain", "url"] },
    { name: "paperclip", component: Paperclip, tags: ["attach"] },
    { name: "printer", component: Printer, tags: ["print"] },
    { name: "refresh", component: RefreshCw, tags: ["reload", "sync"] },
    { name: "rotate", component: RotateCw, tags: ["spin"] },
    { name: "undo", component: Undo, tags: ["back"] },
    { name: "redo", component: Redo, tags: ["forward"] },

    { name: "search", component: Search, tags: ["find", "magnify"] },
    { name: "funnel", component: Funnel, tags: ["filter"] },
    { name: "sliders", component: SlidersHorizontal, tags: ["adjust", "controls"] },
    { name: "eye", component: Eye, tags: ["view", "show"] },
    { name: "eye-off", component: EyeOff, tags: ["hide"] },
    { name: "maximize", component: Maximize, tags: ["expand", "fullscreen"] },
    { name: "minimize", component: Minimize, tags: ["shrink"] },
    { name: "zoom-in", component: ZoomIn, tags: [] },
    { name: "zoom-out", component: ZoomOut, tags: [] },

    { name: "bell", component: Bell, tags: ["notification", "alert"] },
    { name: "bell-ring", component: BellRing, tags: ["notification"] },
    { name: "circle-alert", component: CircleAlert, tags: ["warning"] },
    { name: "triangle-alert", component: TriangleAlert, tags: ["warning"] },
    { name: "info", component: Info, tags: ["information"] },
    { name: "circle-check", component: CircleCheck, tags: ["success", "ok"] },
    { name: "circle-x", component: CircleX, tags: ["error", "cancel", "close"] },
    { name: "circle-question", component: CircleQuestionMark, tags: ["help"] },
    { name: "star", component: Star, tags: ["favorite", "rating"] },
    { name: "heart", component: Heart, tags: ["like", "favorite"] },
    { name: "bookmark", component: Bookmark, tags: ["save", "mark"] },
    { name: "flag", component: Flag, tags: ["report", "mark"] },
    { name: "thumbs-up", component: ThumbsUp, tags: ["like"] },
    { name: "thumbs-down", component: ThumbsDown, tags: ["dislike"] },

    { name: "chart-bar", component: ChartBar, tags: ["graph", "chart"] },
    { name: "chart-bar-stacked", component: ChartBarStacked, tags: ["graph"] },
    { name: "chart-line", component: ChartLine, tags: ["graph", "trend"] },
    { name: "chart-pie", component: ChartPie, tags: ["donut"] },
    { name: "trending-up", component: TrendingUp, tags: ["growth", "up"] },
    { name: "trending-down", component: TrendingDown, tags: ["decline", "down"] },
    { name: "activity", component: Activity, tags: ["pulse"] },
    { name: "gauge", component: Gauge, tags: ["meter", "dashboard"] },
    { name: "database", component: Database, tags: ["data", "storage"] },

    { name: "shopping-cart", component: ShoppingCart, tags: ["ecommerce", "buy"] },
    { name: "shopping-bag", component: ShoppingBag, tags: ["ecommerce"] },
    { name: "credit-card", component: CreditCard, tags: ["payment", "card"] },
    { name: "dollar-sign", component: DollarSign, tags: ["money", "currency"] },
    { name: "tag", component: Tag, tags: ["label", "price"] },
    { name: "gift", component: Gift, tags: ["present"] },
    { name: "wallet", component: Wallet, tags: ["money"] },
    { name: "receipt", component: Receipt, tags: ["invoice", "bill"] },
    { name: "package", component: Package, tags: ["box", "shipping"] },
    { name: "truck", component: Truck, tags: ["shipping", "delivery"] },

    { name: "mail", component: Mail, tags: ["email", "envelope"] },
    { name: "message-square", component: MessageSquare, tags: ["chat", "comment"] },
    { name: "message-circle", component: MessageCircle, tags: ["chat", "comment"] },
    { name: "send", component: Send, tags: ["plane"] },
    { name: "phone", component: Phone, tags: ["call"] },
    { name: "phone-call", component: PhoneCall, tags: [] },
    { name: "video", component: Video, tags: ["camera", "call"] },
    { name: "mic", component: Mic, tags: ["microphone"] },
    { name: "mic-off", component: MicOff, tags: ["muted"] },

    { name: "user", component: User, tags: ["person", "profile"] },
    { name: "users", component: Users, tags: ["people", "team"] },
    { name: "user-plus", component: UserPlus, tags: ["add", "invite"] },
    { name: "user-minus", component: UserMinus, tags: ["remove"] },
    { name: "user-check", component: UserCheck, tags: ["verified"] },
    { name: "user-x", component: UserX, tags: ["blocked"] },
    { name: "shield", component: Shield, tags: ["security"] },
    { name: "shield-check", component: ShieldCheck, tags: ["secure", "verified"] },

    { name: "file", component: File, tags: ["document"] },
    { name: "file-text", component: FileText, tags: ["document"] },
    { name: "file-plus", component: FilePlus, tags: ["new document"] },
    { name: "folder", component: Folder, tags: ["directory"] },
    { name: "folder-open", component: FolderOpen, tags: ["directory"] },
    { name: "folder-plus", component: FolderPlus, tags: [] },
    { name: "image", component: Image, tags: ["picture", "photo"] },

    { name: "calendar", component: Calendar, tags: ["date", "schedule"] },
    { name: "calendar-days", component: CalendarDays, tags: ["date"] },
    { name: "clock", component: Clock, tags: ["time"] },
    { name: "timer", component: Timer, tags: ["stopwatch"] },
    { name: "alarm-clock", component: AlarmClock, tags: ["alert"] },
    { name: "hourglass", component: Hourglass, tags: ["wait", "time"] },

    { name: "settings", component: Settings, tags: ["cog", "preferences"] },
    { name: "settings-2", component: Settings2, tags: ["preferences"] },
    { name: "cog", component: Cog, tags: ["gear"] },
    { name: "key", component: Key, tags: ["password", "access"] },
    { name: "lock", component: Lock, tags: ["private", "secure"] },
    { name: "lock-open", component: LockOpen, tags: ["unlocked"] },
    { name: "log-in", component: LogIn, tags: ["sign in"] },
    { name: "log-out", component: LogOut, tags: ["sign out"] },
    { name: "power", component: Power, tags: ["on", "off"] },
    { name: "cpu", component: Cpu, tags: ["processor"] },
    { name: "server", component: Server, tags: ["hosting"] },
    { name: "hard-drive", component: HardDrive, tags: ["disk"] },
    { name: "wifi", component: Wifi, tags: ["network"] },

    { name: "layers", component: Layers, tags: ["stack"] },
    { name: "palette", component: Palette, tags: ["color"] },
    { name: "brush", component: Brush, tags: ["paint"] },
    { name: "ruler", component: Ruler, tags: ["measure"] },
    { name: "type", component: Type, tags: ["font", "text"] },
    { name: "bold", component: Bold, tags: ["text"] },
    { name: "italic", component: Italic, tags: ["text"] },
    { name: "underline", component: Underline, tags: ["text"] },

    { name: "sun", component: Sun, tags: ["light", "day"] },
    { name: "moon", component: Moon, tags: ["dark", "night"] },
    { name: "cloud", component: Cloud, tags: ["weather"] },
    { name: "cloud-rain", component: CloudRain, tags: ["weather"] },
    { name: "zap", component: Zap, tags: ["lightning", "flash"] },
    { name: "flame", component: Flame, tags: ["fire", "hot"] },
    { name: "droplet", component: Droplet, tags: ["water"] },
    { name: "wind", component: Wind, tags: ["air"] },
    { name: "map-pin", component: MapPin, tags: ["location"] },
    { name: "map", component: Map, tags: ["navigation"] },
    { name: "compass", component: Compass, tags: ["direction"] },
    { name: "globe", component: Globe, tags: ["world", "earth"] },
    { name: "navigation", component: Navigation, tags: ["direction"] },

    { name: "play", component: Play, tags: ["start", "media"] },
    { name: "pause", component: Pause, tags: ["stop", "media"] },
    { name: "skip-back", component: SkipBack, tags: ["previous"] },
    { name: "skip-forward", component: SkipForward, tags: ["next"] },
    { name: "volume", component: Volume, tags: ["sound"] },
    { name: "volume-1", component: Volume1, tags: ["sound"] },
    { name: "volume-2", component: Volume2, tags: ["sound"] },
    { name: "volume-x", component: VolumeX, tags: ["mute"] },

    { name: "sparkles", component: Sparkles, tags: ["magic", "ai"] },
    { name: "rocket", component: Rocket, tags: ["launch"] },
    { name: "trophy", component: Trophy, tags: ["award", "winner"] },
    { name: "target", component: Target, tags: ["goal"] },
    { name: "lightbulb", component: Lightbulb, tags: ["idea"] },
    { name: "flower", component: Flower, tags: ["plant"] },
    { name: "leaf", component: Leaf, tags: ["plant", "eco"] },
    { name: "code", component: Code, tags: ["programming"] },
    { name: "terminal", component: Terminal, tags: ["console"] },
    { name: "bug", component: Bug, tags: ["issue"] },
    { name: "git-branch", component: GitBranch, tags: ["version"] },
    { name: "git-commit", component: GitCommitHorizontal, tags: ["version"] },
    { name: "git-pull-request", component: GitPullRequest, tags: ["version", "pr"] },
    { name: "mouse-pointer", component: MousePointer, tags: ["cursor"] },
    { name: "mouse-pointer-click", component: MousePointerClick, tags: ["cursor"] },
    { name: "pointer", component: Pointer, tags: [] },
    { name: "ellipsis", component: Ellipsis, tags: ["more", "menu"] },
    { name: "ellipsis-vertical", component: EllipsisVertical, tags: ["more", "menu"] },
    { name: "dot", component: Dot, tags: [] },
];

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
    ICON_CATALOG.map((i) => [i.name, i.component]),
);

export function findIcon(name: string): LucideIcon | undefined {
    return ICON_MAP[name];
}

export function searchIcons(query: string, limit = 80): IconEntry[] {
    const q = query.trim().toLowerCase();
    if (!q) return ICON_CATALOG.slice(0, limit);
    return ICON_CATALOG.filter((i) => {
        if (i.name.includes(q)) return true;
        return i.tags.some((t) => t.includes(q));
    }).slice(0, limit);
}
